import Link from 'next/link'
import { getDeps } from '@/server/di'
import { VERSION } from '@/config/version'
// Generated by `npm run evidence` from vitest's own JSON report, ci.yml, and
// eslint.config.mjs; `npm run evidence:check` fails CI if they disagree. These were
// hand-typed until they went stale (423 tests against an actual 463, 5 CI jobs
// against an actual 6) — on a page that argues every number here is checkable.
//
// The test figure is the suite's TOTAL, not a passed count, and that is deliberate:
// two suites are credential-gated, so passed/skipped legitimately differs between a
// machine with credentials and CI without them. The generator refuses to run on a
// failing report, so "zero failures" is checked rather than asserted.
import { EVIDENCE, TEST_SPREAD, TESTS, DAY_ONE_TESTS } from '@/config/evidence'
import * as batchesRepo from '@/repositories/batches.repo'
import { getBatchReport } from '@/app/batch/run-batch'
import { formatPaise, formatMilliInr } from '~/_viz/format'

export const dynamic = 'force-dynamic'

/**
 * A real, verified example from README.md's "The decision model" section — one
 * actual `recovery_audit` row from a live batch run during this project's own
 * verification, not a constructed illustration. Transcribed here rather than
 * queried live because the granular cost breakdown (intervention/compute/risk/
 * fatigue, separately) that `EvExplorer` needs isn't preserved in the README's
 * own combined "Cost" column — recomputing it here would mean inventing a split
 * that was never actually stored. This is the same real numbers, presented, not
 * new numbers.
 */
const WORKED_EXAMPLE = {
  amountPaise: 28900,
  rows: [
    { action: 'RETRY_NOW', pRecover: 0.52, gain: 1.491, cost: 0, ev: null, note: 'excluded — shock-suppressed, a correlated failure burst was active' },
    { action: 'RETRY_LATER', pRecover: 0.96, gain: 2.776, cost: 0, ev: 2.776, note: null },
    { action: 'PAYMENT_LINK', pRecover: 1.08, gain: 3.129, cost: 0.35, ev: 2.779, note: 'chosen — narrowly beats RETRY_LATER' },
    { action: 'WHATSAPP_NUDGE', pRecover: 0.8, gain: 2.322, cost: 0.35, ev: 1.972, note: null },
    { action: 'ESCALATE_HUMAN', pRecover: 1.56, gain: 4.522, cost: 40.0, ev: -35.478, note: 'highest P(recover), deeply negative EV' },
    { action: 'DO_NOTHING', pRecover: 0.57, gain: 1.66, cost: 0, ev: 1.66, note: 'the organic baseline — not zero' },
  ],
  chosenAction: 'PAYMENT_LINK',
} as const

/*
 * Structure follows the design system in app/globals.css (see its header for the
 * provenance note): full-bleed bands
 * alternating true black and light grey, each opened by a pill eyebrow, headings in
 * heavy tight display type with a two-tone treatment, rows numbered [ 01 ] against a
 * hairline rule, white cards on grey separated by contrast rather than borders, and a
 * giant champagne wordmark bleeding across the footer.
 *
 * The content is Reclaim's own, and every figure on this page is derived rather than
 * typed: the self-reported counts come from @/config/evidence (generated, CI-checked),
 * and the batch teaser below is read live from the database and is genuinely absent on
 * a checkout that has never run one. The hero still carries no headline recovery-rate
 * number, and that is deliberate: the batch comparison's outcome draw is model-drawn
 * rather than measured, so promoting it to a hero metric would be the one thing this
 * project cannot afford to do. The worked example carries its own caveat instead.
 */

const RESPONSIBILITIES = [
  {
    n: '01',
    kind: 'Deterministic',
    title: 'Money and state',
    body:
      'State transitions, retry limits, the expected-value arithmetic, idempotency, ' +
      'stopping rules, the audit trail, and every payments API call.',
    points: [
      'Plain TypeScript, unit tested',
      'No model anywhere in the path',
      'Integer paise, never floats',
      'Replayable from a stored input',
    ],
  },
  {
    n: '02',
    kind: 'Statistical',
    title: 'Recovery probability',
    body:
      'A calibrated probability that a failed payment is recoverable, trained offline ' +
      'and checked against a reliability curve rather than assumed.',
    points: [
      'Logistic regression, 25 terms',
      'Calibration checked, not claimed',
      'Runs in process, sub-millisecond',
      'Coefficients readable as JSON',
    ],
  },
  {
    n: '03',
    kind: 'Generative',
    title: 'Language, and only language',
    body:
      'Drafts the recovery message and writes the sentence explaining a decision that ' +
      'has already been made. It never chooses an action.',
    points: [
      'Cannot reach a payments client',
      'Enforced by type, not by comment',
      'Deterministic template fallback',
      'Decide first, then speak',
    ],
  },
] as const


export default async function Home() {
  const deps = await getDeps()
  const { capabilities } = deps

  const mode = capabilities.fullyLocal
    ? 'Local, zero credentials'
    : capabilities.allLive
      ? 'Fully live'
      : 'Mixed, some ports live'

  const maxTests = Math.max(...TEST_SPREAD.map((t) => t.n))

  // A real, live "and today, on this instance" teaser — supporting evidence
  // alongside the worked example above, not a replacement for it. Genuinely
  // absent (not fabricated) on a fresh checkout that has never run a batch.
  const [latestBatch] = await batchesRepo.listRecentLive(deps.sql, 1)
  const liveReport = latestBatch !== undefined ? await getBatchReport(deps, latestBatch.id) : null

  return (
    <main id="main">
      {/* ───────────────────────── HERO, black ───────────────────────── */}
      <section className="bg-ink px-gutter pt-8 pb-band">
        <nav className="mx-auto flex max-w-[1240px] items-start justify-between">
          <span className="display text-[1.0625rem] tracking-[0.06em] uppercase">Reclaim</span>
          <div className="text-right text-[0.625rem] leading-[1.9] tracking-[0.11em] uppercase">
            <Link href="/dashboard" className="text-accent hover:opacity-80">
              Run a batch →
            </Link>
            <div>
              <Link href="/audit" className="text-on-ink-muted hover:text-accent">
                Audit ledger
              </Link>
            </div>
            <div>
              <Link href="/model" className="text-on-ink-muted hover:text-accent">
                Model
              </Link>
            </div>
            <div>
              <Link href="/queue" className="text-on-ink-muted hover:text-accent">
                Queue
              </Link>
            </div>
            <div>
              <Link href="/operator" className="text-on-ink-muted hover:text-accent">
                Escalation queue
              </Link>
            </div>
            <div>
              <Link href="/simulate" className="text-on-ink-muted hover:text-accent">
                Policy simulator
              </Link>
            </div>
          </div>
        </nav>

        <div className="mx-auto mt-band max-w-[1240px]">
          <div className="flex flex-col items-center text-center">
            <span className="eyebrow text-accent">Track: AI Revenue Recovery</span>

            <h1 className="display mt-9 max-w-[17ch] text-hero text-accent">
              Recover what is <span className="text-on-ink-dim">worth</span> recovering
            </h1>
          </div>

          <p className="mx-auto mt-9 max-w-[58ch] text-center text-body text-on-ink-soft">
            Most systems in this space predict whether a payment will fail. Reclaim asks a
            different question: given a payment has already failed, is it worth spending money
            and risk to get it back, and if so, how?
          </p>

          <p className="mx-auto mt-5 max-w-[62ch] text-center text-body text-on-ink-soft">
            A dumb system either retries every failure immediately, or escalates to a human
            whenever the model is most confident. Both optimise probability, not money. Reclaim
            prices every action, including doing nothing, and routinely picks a{' '}
            <span className="text-accent">lower-probability</span> action because it is worth more.
          </p>

          {/* The worked example: a real recovery_audit row, not an illustration. */}
          <div className="mx-auto mt-14 max-w-[880px] bg-ink-raised p-8">
            <span className="text-[0.625rem] tracking-[0.11em] text-accent uppercase">
              One real decision, in full
            </span>
            <p className="mt-4 max-w-[70ch] text-small text-on-ink-soft">
              A {formatPaise(WORKED_EXAMPLE.amountPaise)} invoice, a real row from{' '}
              <code>recovery_audit</code>, from a live batch run during this project&apos;s own
              verification (README.md has the full account). <span className="text-accent">
                ESCALATE_HUMAN
              </span>{' '}
              has by far the highest predicted recovery probability, and by far the worst value —
              a {formatPaise(WORKED_EXAMPLE.amountPaise)} invoice cannot justify a ₹40 human-agent
              cost. <span className="text-accent">PAYMENT_LINK</span> wins instead, narrowly, over
              RETRY_LATER.
            </p>

            <p className="mt-4 max-w-[70ch] text-[0.6875rem] leading-relaxed text-on-ink-muted">
              Said plainly, not buried: the P(recover) values above come from a model trained on
              generated data whose effect sizes are calibrated to be plausible, not measured from
              real transactions — no real payments log records the outcome of an action nobody
              actually took, which is the entire problem synthetic training data exists to work
              around. This is real math, honestly computed, over data this project has never
              claimed is anything but synthetic.
            </p>

            <div className="mt-6 overflow-x-auto">
              <table className="w-full min-w-[560px] border-t border-ink-line text-small">
                <caption className="sr-only">A real EV breakdown, six actions considered for one failed payment</caption>
                <thead>
                  <tr className="border-b border-ink-line text-[0.625rem] tracking-[0.11em] text-on-ink-muted uppercase">
                    <th scope="col" className="py-3 pr-4 text-left font-normal">Action</th>
                    <th scope="col" className="py-3 pr-4 text-right font-normal">P(recover)</th>
                    <th scope="col" className="py-3 pr-4 text-right font-normal">Expected gain</th>
                    <th scope="col" className="py-3 pr-4 text-right font-normal">Cost</th>
                    <th scope="col" className="py-3 text-right font-normal">EV</th>
                  </tr>
                </thead>
                <tbody>
                  {WORKED_EXAMPLE.rows.map((r) => {
                    const isChosen = r.action === WORKED_EXAMPLE.chosenAction
                    return (
                      <tr key={r.action} className={`border-b border-ink-line ${r.ev === null ? 'opacity-40' : ''}`}>
                        <th scope="row" className="py-3 pr-4 text-left align-top font-normal">
                          <span className={isChosen ? 'font-bold text-accent' : 'text-on-ink-soft'}>{r.action}</span>
                          {r.note !== null && <p className="mt-1 max-w-[26ch] text-[0.625rem] text-on-ink-muted">{r.note}</p>}
                        </th>
                        <td className="py-3 pr-4 text-right align-top tnum text-on-ink-soft">{r.pRecover.toFixed(2)}%</td>
                        <td className="py-3 pr-4 text-right align-top tnum text-on-ink-soft">₹{r.gain.toFixed(3)}</td>
                        <td className="py-3 pr-4 text-right align-top tnum text-on-ink-soft">₹{r.cost.toFixed(2)}</td>
                        <td className="py-3 text-right align-top tnum font-bold">
                          {r.ev === null ? (
                            <span className="text-on-ink-muted">excluded</span>
                          ) : (
                            <span className={r.ev >= 0 ? 'text-pos' : 'text-neg'}>₹{r.ev.toFixed(3)}</span>
                          )}
                        </td>
                      </tr>
                    )
                  })}
                </tbody>
              </table>
            </div>

            {liveReport !== null && liveReport.metrics.revenueAtRisk > 0 && (
              <p className="mt-6 max-w-[70ch] text-small text-on-ink-muted">
                And today, on the most recent real batch run through this instance: from{' '}
                {formatPaise(liveReport.metrics.revenueAtRisk)} at risk, Reclaim spent{' '}
                {formatMilliInr(liveReport.policySpend.interventionMilli)} on interventions
                against {formatPaise(liveReport.naiveBaseline.cost)} for retrying every failure
                immediately, and contacted {liveReport.policySpend.touched} of{' '}
                {liveReport.metrics.count} customers. Those are real: arithmetic on the actions{' '}
                <code>decide()</code> chose, with no draw involved.{' '}
                <Link href="/dashboard" className="text-accent hover:opacity-80">
                  See the full batch →
                </Link>
              </p>
            )}
            {liveReport === null && (
              <p className="mt-6 max-w-[70ch] text-small text-on-ink-muted">
                This instance has not run a batch yet.{' '}
                <Link href="/dashboard" className="text-accent hover:opacity-80">
                  Run one from the dashboard
                </Link>{' '}
                to see today&apos;s real numbers alongside this example.
              </p>
            )}
          </div>

          {/* The formula behind that choice, framed like the reference's inset hero card. */}
          <div className="mx-auto mt-14 grid max-w-[880px] gap-px bg-ink-line lg:grid-cols-[1.35fr_1fr]">
            <div className="bg-ink-raised p-8">
              <span className="text-[0.625rem] tracking-[0.11em] text-on-ink-muted uppercase">
                The formula behind that choice
              </span>
              <pre className="mt-6 overflow-x-auto text-small leading-[1.85] text-on-ink-soft">
                <code>
                  {`EV(a) = P(recover | s, a) × RecoverableAmount
        − InterventionCost(a)
        − ComputeCost(a)
        − RiskPenalty(s, a)
        − ContactFatigueCost(s, a)

choose a* = argmax EV(a)`}
                </code>
              </pre>
            </div>

            <div className="flex flex-col justify-between bg-ink-raised p-8">
              <div>
                <span className="text-[0.625rem] tracking-[0.11em] text-accent uppercase">
                  Why it is allowed to do nothing
                </span>
                <p className="mt-5 text-small leading-relaxed text-on-ink-soft">
                  Doing nothing is not zero. Customers retry on their own, so the real quantity
                  is the uplift of acting over not acting. Treating it as zero would credit every
                  intervention with recovery that would have happened anyway.
                </p>
              </div>
              <p className="mt-8 text-[0.625rem] tracking-[0.11em] text-accent-dim uppercase">
                Every action is priced, including none
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ──────────────── CONFIGURATION, black, numbered rows ──────────────── */}
      <section className="bg-ink px-gutter pb-band">
        <div className="mx-auto max-w-[1240px]">
          <span className="eyebrow text-on-ink-muted">Configuration</span>
          <div className="mt-7 flex flex-wrap items-end justify-between gap-6">
            <h2 className="display max-w-[16ch] text-section">What runs where</h2>
            <p className="max-w-[42ch] text-small text-on-ink-muted">
              Every dependency has a real adapter and a local one, chosen by whether a credential
              is present. Absent is never an error. This instance is running in{' '}
              <span className="text-accent">{mode.toLowerCase()}</span>.
            </p>
          </div>

          <ul className="mt-14">
            {capabilities.rows.map((row, i) => (
              <li key={row.port} className="border-t border-ink-line py-5">
                <div className="flex items-baseline justify-between gap-6">
                  <span className="text-small font-bold">{row.port}</span>
                  <span className="numeral text-on-ink-muted">
                    [ {String(i + 1).padStart(2, '0')} ]
                  </span>
                </div>
                <div className="mt-3 flex flex-wrap items-baseline gap-x-6 gap-y-2">
                  <span className="display text-sub text-accent">{row.adapter}</span>
                  <span
                    className="text-[0.625rem] tracking-[0.11em] uppercase"
                    style={{ color: row.live ? 'var(--color-pos)' : 'var(--color-on-ink-muted)' }}
                  >
                    {/* A glyph carries the state as well as the colour. */}
                    {row.live ? '+ live' : '– simulated'}
                  </span>
                </div>
                <p className="mt-3 max-w-[68ch] text-small text-on-ink-muted">{row.reason}</p>
              </li>
            ))}
          </ul>
        </div>
      </section>

      {/* ──────────────── EVIDENCE, light, white cards ──────────────── */}
      <section className="bg-paper px-gutter py-band text-on-paper">
        <div className="mx-auto max-w-[1240px]">
          <span className="eyebrow text-on-paper-muted">Fourteen days in, end to end</span>

          <h2 className="display mt-7 max-w-[30ch] text-section">
            Built so far, and{' '}
            <span className="text-on-paper-dim">
              every number here is checkable by running the command beside it
            </span>
          </h2>

          <div className="mt-14 grid gap-6 lg:grid-cols-[1.15fr_1fr]">
            {/* Bar chart, champagne on white, as in the reference metrics card. */}
            <div className="bg-card p-8">
              <span className="eyebrow text-on-paper-muted">
                Test coverage, day one&apos;s {TEST_SPREAD.length} modules
              </span>
              <p className="display mt-6 max-w-[22ch] text-[1.75rem] leading-[1.1]">
                {TESTS.total} tests today, and real bugs found by running the exit tests, not by
                assuming they&apos;d pass
              </p>
              {/* Named explicitly because the bars below are day one's modules only
                  ({DAY_ONE_TESTS} of {TESTS.total}), not the whole suite — a reader
                  comparing the two numbers should not have to guess why they differ. */}
              <p className="mt-3 text-small text-on-paper-muted">
                The bars are day one&apos;s five modules ({DAY_ONE_TESTS} of {TESTS.total}), not
                the whole suite.
              </p>

              <div className="mt-10 flex h-[168px] items-end gap-4" aria-hidden="true">
                {TEST_SPREAD.map((t) => (
                  <div key={t.module} className="flex flex-1 flex-col items-center gap-3">
                    {/* Champagne fill under a paler cap, as the reference bars do. */}
                    <div
                      className="flex w-full flex-col justify-end"
                      style={{ height: `${(t.n / maxTests) * 130}px` }}
                    >
                      <div className="h-2 w-full bg-accent-deep/35" />
                      <div className="flex-1 w-full bg-accent" />
                    </div>
                    <span className="text-[0.625rem] text-on-paper-muted">{t.module}</span>
                  </div>
                ))}
              </div>

              {/* The same data as a table, so the chart is never the only route to it. */}
              <table className="mt-8 w-full border-t border-paper-line text-small">
                <caption className="sr-only">Unit and property tests per module</caption>
                <tbody>
                  {TEST_SPREAD.map((t) => (
                    <tr key={t.module} className="border-b border-paper-line">
                      <th scope="row" className="py-2 text-left font-normal">
                        {t.module}
                      </th>
                      <td className="py-2 text-right font-bold">{t.n}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Evidence tiles. */}
            <div className="grid gap-6 sm:grid-cols-2">
              {EVIDENCE.map((e) => (
                <div key={e.label} className="flex flex-col justify-between bg-card p-7">
                  <span className="text-[0.625rem] tracking-[0.11em] text-on-paper-muted uppercase">
                    {e.label}
                  </span>
                  <div className="mt-10">
                    <span className="display text-[3rem] leading-none">{e.value}</span>
                    <p className="mt-2 text-small text-on-paper-muted">{e.note}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <p className="mt-10 max-w-[76ch] text-small text-on-paper-muted">
            Built: the decision engine, the trained recovery scorer, the webhook and worker, the
            off-policy evaluation estimators, the language layer, the{' '}
            <Link href="/dashboard" className="text-accent hover:opacity-80">
              batch runner
            </Link>
            , the{' '}
            <Link href="/audit" className="text-accent hover:opacity-80">
              audit ledger and EV explorer
            </Link>
            , the{' '}
            <Link href="/model" className="text-accent hover:opacity-80">
              model
            </Link>{' '}
            and{' '}
            <Link href="/queue" className="text-accent hover:opacity-80">
              queue
            </Link>{' '}
            pages, the{' '}
            <Link href="/simulate" className="text-accent hover:opacity-80">
              policy simulator
            </Link>
            , the{' '}
            <Link href="/operator" className="text-accent hover:opacity-80">
              escalation queue
            </Link>{' '}
            a human actually works — the only place an outcome here comes from a person rather
            than the data generator — and a second B2B receivables-chasing scenario proving the
            engine reuses rather than special-cases. One real, Razorpay-signed webhook delivery has been verified end to end
            through a live tunnel (see docs/SETUP.md), on top of everything the simulator exercises
            in every test and CI run. The sequence and the reasoning behind each choice are in
            BUILD_PLAN.md.
          </p>
        </div>
      </section>

      {/* ──────────────── RESPONSIBILITIES, black ──────────────── */}
      <section className="bg-ink px-gutter py-band">
        <div className="mx-auto max-w-[1240px]">
          <span className="eyebrow text-on-ink-muted">Boundaries</span>
          <h2 className="display mt-7 max-w-[22ch] text-section">
            Where the model is, and where it deliberately is not
          </h2>

          <div className="mt-16">
            {RESPONSIBILITIES.map((r) => (
              <article key={r.n} className="border-t border-ink-line pt-5 pb-14">
                <div className="flex items-baseline justify-between gap-6">
                  <span className="text-small font-bold">{r.kind}</span>
                  <span className="numeral text-on-ink-muted">[ {r.n} ]</span>
                </div>

                <div className="mt-6 grid gap-10 lg:grid-cols-[1.3fr_1fr]">
                  <div>
                    <h3 className="display text-sub">{r.title}</h3>
                    <p className="mt-5 max-w-[52ch] text-small text-on-ink-muted">{r.body}</p>
                  </div>
                  <ul className="space-y-3 self-end">
                    {r.points.map((p) => (
                      <li key={p} className="flex items-baseline gap-3 text-small text-on-ink-soft">
                        <span aria-hidden="true" className="text-accent">
                          +
                        </span>
                        {p}
                      </li>
                    ))}
                  </ul>
                </div>
              </article>
            ))}
          </div>

          <div className="bracketed mt-6 px-6 py-20 text-center">
            <p className="display mx-auto max-w-[26ch] text-section">
              The language layer <span className="text-on-ink-dim">cannot</span> reach a
              payments client
            </p>
            <p className="mx-auto mt-7 max-w-[62ch] text-small text-on-ink-muted">
              Enforced five ways, two of them at the type level, and one of them an ordering
              guarantee stronger than the rest: the decision has already been made before any
              language call happens, and the result carries no action field.
            </p>
          </div>
        </div>
      </section>

      {/* ──────────────── FOOTER, giant wordmark ──────────────── */}
      <footer className="bg-ink px-gutter pb-12">
        <div className="mx-auto max-w-[1240px]">
          <div
            className="display leading-[0.78] text-accent"
            style={{ fontSize: 'clamp(4rem, 19vw, 17rem)', letterSpacing: '-0.04em' }}
            aria-hidden="true"
          >
            RECLAIM
          </div>

          <div className="mt-12 grid gap-10 border-t border-ink-line pt-10 sm:grid-cols-3">
            <p className="max-w-[38ch] text-small text-on-ink-muted">
              Risk-aware revenue recovery. It prices every recovery action, including doing
              nothing.
            </p>
            <div className="text-small">
              <span className="text-[0.625rem] tracking-[0.11em] text-on-ink-muted uppercase">
                Reference
              </span>
              <ul className="mt-4 space-y-2 text-on-ink-soft">
                <li>BUILD_PLAN.md</li>
                <li>SYSTEM_SPEC.md</li>
                <li>docs/INCIDENTS.md</li>
              </ul>
            </div>
            <div className="text-small sm:text-right">
              <span className="text-[0.625rem] tracking-[0.11em] text-on-ink-muted uppercase">
                Constraints
              </span>
              <ul className="mt-4 space-y-2 text-on-ink-soft">
                <li>Synthetic data only</li>
                <li>Test-mode credentials only</li>
                <li>Bounded, reversible actions</li>
              </ul>
            </div>
          </div>

          <div className="mt-10 flex flex-wrap justify-between gap-4 text-[0.625rem] tracking-[0.11em] text-on-ink-muted uppercase">
            <span>Version {VERSION}</span>
            <span>{mode}</span>
          </div>
        </div>
      </footer>
    </main>
  )
}
