"""
Off-policy evaluation for the B2B receivables scenario — a structural port of
`scripts/data/run_ope.py`, closing a real gap: subscription had a full
DM/SNIPS/DR six-policy bracket (BUILD_PLAN.md §6.4/§6.5); B2B, despite having
identical raw materials (`oracle_counterfactuals.parquet`, `risk_eval_demo.csv`,
`customers.csv` all already generated by `scripts/data_b2b/generate.py`), never
had this evaluation built at all. Reuses `scripts/data/ope.py`'s estimator math
directly (`ope.dm`/`ope.snips`/`ope.dr`/`ope.ess`/`ope.bootstrap_ci`) — that
module is pure statistics with no subscription-specific data in it, so
importing it is not a second copy of anything, the same reasoning
`scripts/data_b2b/common.py`'s own docstring gives for reading
`src/domain/risk/rules.ts`'s shared risk weights rather than re-deriving them.

Usage: `npm run ope:b2b` (== `python -m scripts.data_b2b.run_ope`). Writes
`docs/ope_results_b2b.json` — a SEPARATE file from subscription's
`docs/ope_results.json`, never overwriting it.
"""
from __future__ import annotations

import json

import numpy as np
import pandas as pd

from .common import ACTIONS, OUT_DIR, SEED
from .q_hat import load_model, p_recover
from .reward import reward_paise
from . import policies as pol
from scripts.data import ope

PAISE_PER_RUPEE = 100


def _load() -> tuple[pd.DataFrame, dict]:
    demo = pd.read_csv(OUT_DIR / "logged_demo.csv")
    customers = pd.read_csv(OUT_DIR / "customers.csv")[["customer_id", "typical_invoice_paise"]]
    risk = pd.read_csv(OUT_DIR / "risk_eval_demo.csv").drop(columns=["amount_paise", "event_created_at"])
    oracle = pd.read_parquet(OUT_DIR / "oracle_counterfactuals.parquet")

    df = demo.merge(customers, on="customer_id", how="left", validate="many_to_one")
    df = df.merge(risk, on="event_id", how="left", validate="one_to_one")
    df = df.merge(oracle, on="event_id", how="left", validate="one_to_one")
    assert df["typical_invoice_paise"].notna().all(), "every demo row must join a customer"
    assert df["is_truly_risky"].notna().all(), "every demo row must join its oracle counterfactuals"

    model = load_model(OUT_DIR / "recovery_model.json")
    return df, model


def _features_of(row) -> dict:
    return {
        "days_overdue": row["days_overdue"],
        "customer_ontime_rate": row["customer_ontime_rate"],
        "invoice_size_zscore": row["invoice_size_zscore"],
        "chase_rounds_so_far": row["chase_rounds_so_far"],
        "is_repeat_overdue_this_quarter": row["is_repeat_overdue_this_quarter"],
        "quarter_sin": row["quarter_sin"],
        "quarter_cos": row["quarter_cos"],
        "contacts_last_14d": row["contacts_last_14d"],
        "customer_relationship_days": row["customer_relationship_days"],
    }


def _oracle_reward_at(row, action: str) -> float:
    y = row[f"y_true_{action}"]
    return reward_paise(action, y, row["amount_paise"], row["contacts_last_14d"], row["typical_invoice_paise"])


def _prepare_rows(df: pd.DataFrame, model: dict) -> pd.DataFrame:
    records = []
    for row in df.itertuples(index=False):
        r = row._asdict()
        features = _features_of(r)
        qhats = {a: p_recover(model, features, a) for a in ACTIONS}
        r["q_logged"] = reward_paise(
            r["action"], qhats[r["action"]], r["amount_paise"], r["contacts_last_14d"], r["typical_invoice_paise"]
        )
        r["r"] = reward_paise(
            r["action"], r["outcome"], r["amount_paise"], r["contacts_last_14d"], r["typical_invoice_paise"]
        )
        for a in ACTIONS:
            r[f"qhat_{a}"] = reward_paise(
                a, qhats[a], r["amount_paise"], r["contacts_last_14d"], r["typical_invoice_paise"]
            )
        r["reclaim_action"] = pol.reclaim_action(r, model, features)
        records.append(r)
    return pd.DataFrame.from_records(records)


def _lookup_qhat(df: pd.DataFrame, chosen: np.ndarray) -> np.ndarray:
    out = np.empty(len(df))
    for a in ACTIONS:
        mask = chosen == a
        out[mask] = df.loc[mask, f"qhat_{a}"].to_numpy()
    return out


def _evaluate_deterministic(name: str, chosen: np.ndarray, df: pd.DataFrame, rng: np.random.Generator) -> dict:
    logged_action = df["action"].to_numpy()
    propensity = df["propensity"].to_numpy()
    w = ope.importance_weight(chosen, logged_action, propensity)
    q_chosen = _lookup_qhat(df, chosen)
    q_logged = df["q_logged"].to_numpy()
    r = df["r"].to_numpy()

    value_dm = ope.dm(q_chosen)
    value_snips = ope.snips(w, r)
    value_dr = ope.dr(q_chosen, w, r, q_logged)
    value_ess = ope.ess(w)

    def dr_estimator(w, r, q_chosen, q_logged):
        return ope.dr(q_chosen, w, r, q_logged)

    ci_lo, ci_hi = ope.bootstrap_ci(dr_estimator, rng, w=w, r=r, q_chosen=q_chosen, q_logged=q_logged)

    oracle_value = float(
        np.mean([_oracle_reward_at(row, a) for row, a in zip(df.to_dict("records"), chosen)])
    ) / PAISE_PER_RUPEE

    value_dr_inr = value_dr / PAISE_PER_RUPEE
    return {
        "policy": name,
        "estimator": "doubly_robust",
        "value_inr": value_dr_inr,
        "ci_low_inr": ci_lo / PAISE_PER_RUPEE,
        "ci_high_inr": ci_hi / PAISE_PER_RUPEE,
        "dm_inr": value_dm / PAISE_PER_RUPEE,
        "snips_inr": value_snips / PAISE_PER_RUPEE,
        "ess": value_ess,
        "ess_trustworthy": value_ess >= ope.ESS_UNTRUSTWORTHY_BELOW,
        "n": len(df),
        "oracle_value_inr": oracle_value,
        "estimator_error_pct": abs(value_dr_inr - oracle_value) / abs(oracle_value) * 100 if oracle_value != 0 else float("nan"),
    }


def _evaluate_b4_logging_policy(df: pd.DataFrame, rng: np.random.Generator) -> dict:
    r = df["r"].to_numpy()
    value = float(np.mean(r))
    boot = np.empty(ope.N_BOOTSTRAP)
    n = len(r)
    for b in range(ope.N_BOOTSTRAP):
        idx = rng.integers(0, n, size=n)
        boot[b] = np.mean(r[idx])
    lo, hi = np.percentile(boot, [2.5, 97.5])
    oracle_value = float(np.mean([_oracle_reward_at(row, row["action"]) for row in df.to_dict("records")])) / PAISE_PER_RUPEE
    value_inr = value / PAISE_PER_RUPEE
    return {
        "policy": "B4",
        "estimator": "on_policy_mean",
        "value_inr": value_inr,
        "ci_low_inr": lo / PAISE_PER_RUPEE,
        "ci_high_inr": hi / PAISE_PER_RUPEE,
        "dm_inr": value_inr,
        "snips_inr": value_inr,
        "ess": float(n),
        "ess_trustworthy": True,
        "n": n,
        "oracle_value_inr": oracle_value,
        "estimator_error_pct": abs(value_inr - oracle_value) / abs(oracle_value) * 100 if oracle_value != 0 else float("nan"),
    }


def _evaluate_b5_oracle(df: pd.DataFrame) -> dict:
    def best(row) -> float:
        return max(_oracle_reward_at(row, a) for a in ACTIONS)

    values = [best(row) for row in df.to_dict("records")]
    return {
        "policy": "B5",
        "estimator": "oracle_simulator",
        "value_inr": float(np.mean(values)) / PAISE_PER_RUPEE,
        "ci_low_inr": None, "ci_high_inr": None, "dm_inr": None, "snips_inr": None,
        "ess": None, "ess_trustworthy": None,
        "n": len(df),
        "oracle_value_inr": None, "estimator_error_pct": None,
        "note": "Oracle-file only, per-event single-decision optimum. Not comparable to an estimator error, it is the ground truth.",
    }


def _evaluate_b2_sequential(df: pd.DataFrame) -> dict:
    """B2B's own sequential baseline: chase every round with SEND_REMINDER —
    the cheapest contact-requiring action — up to `MAX_RETRIES` (2), stopping
    on success, using each observed attempt's own realised state (not a
    re-simulated one). Same documented limitation as subscription's B2
    (`scripts/data/run_ope.py`'s own docstring): single-step (SN)IPS/DR cannot
    validly evaluate a sequential policy, so this simulates directly against
    the oracle counterfactuals instead, over each invoice's observed chase
    chain rather than a hypothetical always-SEND_REMINDER trajectory the
    generator was never asked to emit."""
    values = []
    for _invoice_id, group in df.groupby("invoice_id"):
        group = group.sort_values("chase_rounds_so_far")
        total = 0.0
        for row in group.to_dict("records"):
            y = row["y_true_SEND_REMINDER"]
            total += reward_paise(
                "SEND_REMINDER", y, row["amount_paise"], row["contacts_last_14d"], row["typical_invoice_paise"]
            )
            if y == 1:
                break
        values.append(total)
    return {
        "policy": "B2",
        "estimator": "oracle_simulator",
        "value_inr": float(np.mean(values)) / PAISE_PER_RUPEE,
        "ci_low_inr": None, "ci_high_inr": None, "dm_inr": None, "snips_inr": None,
        "ess": None, "ess_trustworthy": None,
        "n": df["invoice_id"].nunique(),
        "oracle_value_inr": None, "estimator_error_pct": None,
        "note": "Oracle-simulator only, per-invoice chase chain. See docstring: single-step importance weighting is invalid for a sequential policy, and this simulation reuses observed (not re-simulated) state transitions between chase rounds.",
    }


def main() -> None:
    rng = np.random.default_rng(SEED)
    df, model = _load()
    df = _prepare_rows(df, model)

    results = []
    results.append(_evaluate_deterministic("B0", np.full(len(df), "WRITE_OFF"), df, rng))
    results.append(_evaluate_deterministic("B1", np.full(len(df), "SEND_REMINDER"), df, rng))
    results.append(_evaluate_b2_sequential(df))
    results.append(_evaluate_deterministic("B3", np.full(len(df), "OFFER_PAYMENT_PLAN"), df, rng))
    results.append(_evaluate_b4_logging_policy(df, rng))
    results.append(_evaluate_deterministic("Reclaim", df["reclaim_action"].to_numpy(), df, rng))
    results.append(_evaluate_b5_oracle(df))

    by_policy = {r["policy"]: r for r in results}
    v_b4 = by_policy["B4"]["value_inr"]
    v_b5 = by_policy["B5"]["value_inr"]
    v_reclaim = by_policy["Reclaim"]["value_inr"]
    headroom_captured = (v_reclaim - v_b4) / (v_b5 - v_b4) if v_b5 != v_b4 else float("nan")

    out = {
        "seed": int(SEED),
        "split": "logged_demo",
        "scenario": "b2b_receivable",
        "n_events": len(df),
        "n_invoices": int(df["invoice_id"].nunique()),
        "policies": results,
        "headroom_captured": headroom_captured,
        "bracket_order_expected": ["B0", "B1", "B2", "B3", "B4", "Reclaim", "B5"],
        "bracket_order_actual": [r["policy"] for r in sorted(results, key=lambda r: r["value_inr"])],
    }

    out_path = OUT_DIR.parent.parent.parent / "docs" / "ope_results_b2b.json"
    out_path.write_text(json.dumps(out, indent=2), encoding="utf-8", newline="\n")

    print(f"\nOff-policy evaluation, B2B receivables — {out['split']} ({out['n_events']} events, {out['n_invoices']} invoices)\n")
    header = f"{'Policy':<10}{'Estimator':<18}{'Value (Rs/event)':<20}{'95% CI':<24}{'ESS':<10}{'Oracle':<12}{'Error %':<10}"
    print(header)
    print("-" * len(header))
    for r in results:
        ci = f"[{r['ci_low_inr']:.2f}, {r['ci_high_inr']:.2f}]" if r["ci_low_inr"] is not None else "n/a"
        ess_s = f"{r['ess']:.0f}" if r["ess"] is not None else "n/a"
        oracle_s = f"{r['oracle_value_inr']:.2f}" if r["oracle_value_inr"] is not None else "n/a"
        err_s = f"{r['estimator_error_pct']:.1f}" if r["estimator_error_pct"] is not None else "n/a"
        print(f"{r['policy']:<10}{r['estimator']:<18}{r['value_inr']:<20.2f}{ci:<24}{ess_s:<10}{oracle_s:<12}{err_s:<10}")

    print(f"\nBracket order (ascending value): {' <= '.join(out['bracket_order_actual'])}")
    print(f"Expected order:                  {' <= '.join(out['bracket_order_expected'])}")
    print(f"HeadroomCaptured = (Reclaim - B4) / (B5 - B4) = {headroom_captured:.1%}")
    print(f"\nWritten: {out_path}")


if __name__ == "__main__":
    main()
